version: '3.8'

services:
  run-model-locally:
    container_name: objects-model-local-starter
    restart: "no"
    image: tianon/true:multiarch
    depends_on:
      - objects-model

  objects-model:
    container_name: objects-model
    command: poetry run flask run
    build:
      context: .
    image: objects-model:latest
    restart: unless-stopped
    volumes:
      - .:/app-workspace
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      - objects-model-postgres
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 7gb
    ports:
      - "7541:5000"

  objects-model-postgres:
    container_name: objects-model-postgres
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - objects-model-postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER"
      timeout: 10s
      interval: 10s
      retries: 3
    networks:
      - internal
    env_file:
      - .env
    ports:
      - "7540:5432"

networks:
  internal: {}

volumes:
  objects-model-postgres-data: