"""

Revision ID: 386e6624a382
Revises: 
Create Date: 2024-05-25 15:43:49.441665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386e6624a382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_object',
    sa.Column('photo_id', sa.BigInteger(), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('photo_id', 'object_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_object')
    op.drop_table('objects')
    # ### end Alembic commands ###
