image:
  registry: ghcr.io
  repository: tourmalinecore/tourmanique-object-service
  tag: "latest"
  pullPolicy: Always
  debug: false
  
command:
  - "poetry"
args:
  - "run"
  - "flask"
  - "run"

podAnnotations:
  checksum/config: "{{ include (print $.Template.BasePath \"/extra-list.yaml\") . | sha256sum }}"

containerPorts:
  http: 5000
  https: ""

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

bindURLs: http://+:5000

replicaCount: 1

resources:
  limits:
    cpu: 2000m
    memory: 5Gi
  requests:
    cpu: 1000m
    memory: 2Gi

service:
  type: ClusterIP
  ports:
    http: 5000
    https: ""

ingress:
  enabled: true
  path: /objects-service(/|$)(.*)
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt 
    nginx.ingress.kubernetes.io/rewrite-target: /objects-service/$2
  ingressClassName: "nginx"
  tls: true

extraConfigMapEnvVars: {}

# this is needed to tell the container to read extra env vars from the dedicated Config Map that we create in extraDeploy
extraEnvVarsCM: "{{ include \"common.names.fullname\" . }}"

extraConfigMapEnvVarsEncoded: |
  {{- range $k, $v := .Values.extraConfigMapEnvVars }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}

extraDeploy:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ include "common.names.fullname" . }}
      namespace: {{ include "common.names.namespace" . | quote }}
      labels: {{- include "common.labels.standard" . | nindent 6 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
        {{- end }}
      {{- if .Values.commonAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
      {{- end }}
    data:
      {{- if .Values.extraConfigMapEnvVars }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.extraConfigMapEnvVars "context" $ ) | nindent 6 }}
      {{- end }}